### ISSUE TITLE
nginx core dump

### ISSUE THREAD

**Issue by zhaibin18** [cuber/ngx_http_google_filter_module#148]
`Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: w'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004f8ba5 in ngx_http_google_create_ctx (r=0x1072760) at /home/zhaibin18/build_home/nginx-1.14.0/ngx_http_google_filter_module/src/ngx_http_google_request.c:41
41        ngx_str_t domain = *ctx->host;
(gdb) bt
#0  0x00000000004f8ba5 in ngx_http_google_create_ctx (r=0x1072760) at /home/zhaibin18/build_home/nginx-1.14.0/ngx_http_google_filter_module/src/ngx_http_google_request.c:41
#1  0x00000000004f9d94 in ngx_http_google_request_handler (r=0x1072760)
    at /home/zhaibin18/build_home/nginx-1.14.0/ngx_http_google_filter_module/src/ngx_http_google_request.c:429
#2  0x000000000046f0b9 in ngx_http_core_rewrite_phase (r=0x1072760, ph=0x109b558) at src/http/ngx_http_core_module.c:912
#3  0x000000000046ef15 in ngx_http_core_run_phases (r=0x1072760) at src/http/ngx_http_core_module.c:858
#4  0x000000000046ee82 in ngx_http_handler (r=0x1072760) at src/http/ngx_http_core_module.c:841
#5  0x000000000047eb54 in ngx_http_process_request (r=0x1072760) at src/http/ngx_http_request.c:1952
#6  0x000000000047d4d6 in ngx_http_process_request_headers (rev=0x109fcb0) at src/http/ngx_http_request.c:1379
#7  0x000000000047c881 in ngx_http_process_request_line (rev=0x109fcb0) at src/http/ngx_http_request.c:1052
#8  0x000000000047b35d in ngx_http_wait_request_handler (rev=0x109fcb0) at src/http/ngx_http_request.c:510
#9  0x000000000045b61e in ngx_epoll_process_events (cycle=0x106e750, timer=59756, flags=1) at src/event/modules/ngx_epoll_module.c:902
#10 0x000000000044895f in ngx_process_events_and_timers (cycle=0x106e750) at src/event/ngx_event.c:242
#11 0x0000000000458ac4 in ngx_worker_process_cycle (cycle=0x106e750, data=0x0) at src/os/unix/ngx_process_cycle.c:750
#12 0x00000000004550de in ngx_spawn_process (cycle=0x106e750, proc=0x4589dd <ngx_worker_process_cycle>, data=0x0, name=0x5039bb "worker process", respawn=0)
    at src/os/unix/ngx_process.c:199
#13 0x0000000000458561 in ngx_reap_children (cycle=0x106e750) at src/os/unix/ngx_process_cycle.c:622
#14 0x00000000004570ac in ngx_master_process_cycle (cycle=0x106e750) at src/os/unix/ngx_process_cycle.c:175
#15 0x0000000000411211 in main (argc=1, argv=0x7ffc97764048) at src/core/nginx.c:382
(gdb)
`

**Comment by cuber** [comment]
可否复现？

**Comment by zhaibin18** [comment]
可以复现，需要什么debug信息我可以继续抓。

**Comment by cuber** [comment]
你把core掉的请求url贴一下

**Comment by zhaibin18** [comment]
不是访问某个特定的url就core dump了，经常是半夜没人访问的时候某个线程core dump。
